### ISSUE TITLE
ConnectionApprovalDelegate doesn't exist in Network Manager.

### ISSUE THREAD

**Issue by ritikwalgaonkar** [DapperDino/Unity-Multiplayer-Tutorials#8]
Assets\Tutorials\ObjectSpawning\Scripts\PasswordNetworkManager.cs(91,90): error CS0426: The type name 'ConnectionApprovedDelegate' does not exist in the type 'NetworkManager'

https://github.com/DapperDino/Unity-Multiplayer-Tutorials/blob/main/Assets/Tutorials/ObjectSpawning/Scripts/PasswordNetworkManager.cs
line no.91

Only works in package (netcode for objects 1.0.0-pre.3) , doesn't work in updated packages of netcode. @DapperDino

**Comment by FrothyPants** [comment]
@ritikwalgaonkar that callback has been renamed to `ConnectionApprovalCallback `and has changed somewhat. Just update it with the docs shown here. 
https://docs-multiplayer.unity3d.com/netcode/current/basics/connection-approval

**Comment by fenix1stroke** [comment]
@FrothyPants hey, sorry to bother - I am quite new to C# - but how would you implement the usage of the method ApprovalCheck in lines 44 and 60 of the ServerGameNetPortal.cs ? I changed the method itself so it would assign the needed values to the response but I do not understand the usage of += and -= on the ConnectionApprovalCallback event(?). Like how can we call ApprovalCheck without passing arguments?

My VS tells me: "No Overload for 'ApprovalCheck' matches delegate 'Action<NetworkManager.ConnectionApprovalRequest, NetworkManager.ConnectionApprovalResponse>"

![image](https://user-images.githubusercontent.com/116453707/207180641-65e9b7c4-f5c4-4d68-8db3-2cc6bb07f144.png)

Best Regards
